project:
  type: website
  output-dir: docs

website:
  title: "patrickabolger.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bio.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

