project:
  type: website
  output-dir: docs

website:
  title: "Patrick A. Bolger"
  site-url: https://patrickabolger.github.io/
  navbar:
    left:
      - href: source/index.qmd
        text: Home
      - source/bio.qmd
      - source/teaching.qmd
      - source/research.qmd

format:
  html:
    embed-resources: true
    self-contained: true
    theme: 
      light: minty
      dark: solar
    toc: true
    page-layout: full
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true

editor: source

