---
title: "Teaching"
toc: false
about: 
  template: solana
---

## Teaching Philosophy

We should foster learning through student-centered teaching, where the instructor acts more as a mentor and facilitator than as a lecturer. In my opinion, the best learning, be it at the undergraduate or graduate level, takes place through active learning as students work on projects tailored to their own interests. 

That said, it has been a challenge to implement this kind of learning in the large courses that I have often taught (e.g., 100-300 students). Nonetheless, it was fairly easy to do in the lab sections of my statistics courses at Texas A&M. In small groups, my students would develop their own surveys in Google Forms, collect data, and then analyse it for their individual [IMRaD](https://en.wikipedia.org/wiki/IMRAD){target="_blank"} papers (see [here](https://patrickabolger.github.io/PSYC-301-Syllabus-Spring-2022/#tasks-in-lab){target="_blank"} for a description of the labs in my most recent syllabus for that course). Student-centered learning is also difficult to implement in statistics courses in general, where students often need explicit instructor help in order to understand the material. But carefully planned small-group projects go a long way in making the student the center of instruction.

## Teaching Experience

I have a good deal of experience teaching various subjects, but what energizes me most nowadays is teaching statistics and research methods in higher education. As you can see from my [formal education](cv.qmd) , I did not take the direct route to this point.

::: {.panel-tabset}

## Nottingham Trent University (2024-present)

In February 2024 I was hired as a Senior Lecturer in [Psychology](https://www.ntu.ac.uk/study-and-courses/academic-schools/social-sciences/psychology){target="_blank"} at [Nottingham Trent University](https://www.ntu.ac.uk/){target="_blank"} in Nottingham, United Kingdom.

At NTU I have taught several modules[^1] (click [here](index.qmd) to see a list, or just go to the `Home` tab above). I have also supervised several third-year student projects. So far, I have learned much more about the teaching ecosystem in the UK than I have about classroom teaching itself (which is ultimately similar to classroom teaching in the US).

I was also the leader for four modules (where modules are usually taught by multiple lecturers at NTU). 

I have served as a personal tutor at both the undergraduate and postgraduate levels. Personal tutors in the UK take responsibility for a select group of students (their *tutees*). This responsibility includes teaching them (usually general academic skills), tracking their progress, and pointing them to the appropriate resources when academic or personal issues arise.

Finally, I have served as both the year-one tutor for the general pathway in Single Honours and the year-three tutor for Combined Honours. This are positions with the Course Team. Towards the beginning of the academic year, the bulk of the work is working with student access statements. Towards the end of the year, the workload shifts to consulting with students who have missed assessments. The year tutors also participate in their respective year-end Exam Boards, where decisions are made about whether students have completed all their assessments and move on to year 2, and if not, how they might do so during the referral period, or be allowed to trail work into year 2, or be required to repeat year one.

## Texas A&M University (2016-2022)

In 2016 I was hired as an Instructional Assistant Professor in the Department of Psychological and Brain Sciences at Texas A&M University. There, the vast majority of my responsibilities comprised teaching [undergraduate statistics](https://patrickabolger.github.io/PSYC-301-Syllabus-Spring-2022/){target="_blank"}, [graduate statistics](https://patrickabolger.github.io/PSYC-652-Fall-2020/){target="_blank"}, and [undergraduate research methods](https://patrickabolger.github.io/PSYC-245-Spring-2022/){target="_blank"}. But I also taught *Developmental Psychology* and *Psychology of Language*.

To be honest, I was rather surprised at how enthusiastic I became in teaching statistics and research methods. The course I taught most frequently, by far, was *Elementary Statistics for Psychology*, a course with large sections (usually about 100 students each), with multiple branching labs that also required that each student write an IMRaD paper (*Introduction*, *Methods*, *Results*, and *Discussion*). It was here that I implemented most of my innovations, including most notably, the following:

#### Open educational resources

By the time I had left Texas A&M, I had managed to incorporate exclusively open educational resources into the course. Doing so reduces the financial burden on students, thereby helping not only to reduce their overall stress levels, but also (by extension) to maximize their learning potential. Specifically, I did the following:

- assigned a free, high-quality textbook, [learning statistics with jamovi](https://davidfoxcroft.github.io/lsj-book/){target="_blank"}  
- had them use the free statistical software, [jamovi](https://www.jamovi.org/){target="_blank"}, for analyses  
- wrote a new [lab manual](https://patrickabolger.github.io/ElemStatsLabManual/){target="_blank"} for the course (since the other manual in use was designed for SPSS)

#### Reducing student anxiety

I transferred the mathematical calculations traditionally required on exams to for-credit, but repeatable homework assignments. This involved setting up math-based problems using the [exams](https://www.r-exams.org/){target="_blank"} package in [R](https://www.r-project.org/){target="_blank"}. Some of those assignments can be found [here](https://github.com/patrickabolger/stats-exam-questions){target="_blank"}.


## University of Alberta (2005-2012)

After obtaining my PhD, I was hired in the Department of Linguistics at the University of Alberta. I usually taught courses related to my PhD expertise (e.g., *Psychology of Language*, *Introduction to Linguistics*, *Child Language Acquisition*).

But I was also heavily engaged in research at the time, learning a great deal not only about new research methodologies, but also about more modern approaches to statistical analysis, like mixed-effects modeling. This became important to my teaching later.

At the same time, I was mentoring many, many graduate and undergraduate students in how to design and run behavioural, eyetracking and ERP experiments.

After seven years at the University of Alberta, I resigned in 2012 in order to take care of a family member in desperate need. Since academia is far too competitive to be able to accommodate cases like mine, that career hiatus ultimately spelled the end of my research trajectory.

<!-- ## University of Arizona (1999-2005) -->

<!-- This continued while I was a PhD student a few, short years later. I often taught Freshman Composition to support myself as an interdisciplinary PhD student of applied psycholinguistics at the University of Arizona. -->

<!-- ## Monterey Institute (1997-1999) -->

<!-- After getting my MA in TESOL from the Monterey (now Middlebury) Institute of International Studies in 1997, I began teaching English in an ESL context. It didn't take long before I was frequently being tapped to teach advanced grammar and academic writing. -->

[^1]: A *module* in the UK is a *course* or *class* in the US.
:::